/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ai.chess;

import java.awt.BorderLayout;
import java.awt.Component;
import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author omarashour
 */
public class GameIntro extends javax.swing.JFrame implements Serializable{

    /**
     * Creates new form GameIntro
     */
    public GameIntro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        startBtn = new javax.swing.JButton();
        startBtn1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        startBtn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/intro.gif"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(20, 2, 2));
        jLabel2.setText("AI CHESS");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(194, 36, 36));
        jLabel3.setText("Only Legends Can Defeat This ;) ");

        startBtn.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        startBtn.setForeground(new java.awt.Color(195, 134, 45));
        startBtn.setText("Singleplayer");
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        startBtn1.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        startBtn1.setForeground(new java.awt.Color(255, 0, 204));
        startBtn1.setText("Load Game");
        startBtn1.setToolTipText("");
        startBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtn1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Multiplayer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        startBtn2.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        startBtn2.setForeground(new java.awt.Color(255, 0, 0));
        startBtn2.setText("Exit");
        startBtn2.setToolTipText("");
        startBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel3)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(146, 146, 146))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(startBtn)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(startBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(startBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed
        try {
            // TODO add your handling code here:
            String[] options = {"White", "Black"};
            int choice = JOptionPane.showOptionDialog(null, "Choose Whether you want to play with White or Black?", "",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);

            if (choice == 0) {

                ChessBoard chessBoard = new ChessBoard();
                AIChess.isPlayerWhite = true;
                SingleBoardPanel boardPanel = new SingleBoardPanel(chessBoard);
                GameBoard gb = new GameBoard(boardPanel);
                gb.setVisible(true);
            } else if (choice == 1) {
                ChessBoard chessBoard = new ChessBoard();
                AIChess.isPlayerWhite=false;
                SingleBoardPanel boardPanel = new SingleBoardPanel(chessBoard);
                GameBoard gb = new GameBoard(boardPanel);
                this.setVisible(false);
                gb.setVisible(true);
            } else {
                System.exit(0);
            }

        } catch (IOException ex) {
            System.out.println("Exception in Class GameIntro.java in the part from line 123 to 144");
        }
    }//GEN-LAST:event_startBtnActionPerformed

    private void startBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtn1ActionPerformed
        // TODO add your handling code here:
        LoadFrame loadframe = new LoadFrame();
        System.err.println("hiiii");
        loadframe.setVisible(true);
    }//GEN-LAST:event_startBtn1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ChessBoard chessBoard;
        try {
            chessBoard = new ChessBoard();
            MultiBoardPanel multiBoardPanel = new MultiBoardPanel(chessBoard);
            GameBoard gb = new GameBoard(multiBoardPanel);
            this.setVisible(false);
            gb.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(GameIntro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void startBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtn2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_startBtn2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton startBtn;
    private javax.swing.JButton startBtn1;
    private javax.swing.JButton startBtn2;
    // End of variables declaration//GEN-END:variables
}
