/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ai.chess;

import static ai.chess.AIChess.*;
import java.io.Serializable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class LoadPanel extends javax.swing.JPanel implements Serializable {

    /**
     * Creates new form LoadFrame
     */
    DefaultTableModel model;

    public LoadPanel() {
        initComponents();
        model = (DefaultTableModel) savedPanelTable.getModel();
        if (savedPanelsList.isEmpty()) {
            System.err.println("uhdfjk");
        }
        for (SavedPanel savedPanel : savedPanelsList) {

            model.addRow(new Object[]{savedPanel.dateTime, savedPanel.Type});
            System.err.println("hfjkl");
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        savedPanelTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        loadButton = new javax.swing.JButton();

        setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N

        savedPanelTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date & Time", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(savedPanelTable);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        jLabel1.setText("Select The Game To Load ! ");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        loadButton.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        loadButton.setForeground(new java.awt.Color(0, 204, 0));
        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(loadButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loadButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
        SavedPanel sp = savedPanelsList.get(savedPanelTable.getSelectedRow());

        isPlayerWhite = sp.isPlayerWhite;

        if (sp.Type.equals("Singleplayer")) {
            SingleBoardPanel single = new SingleBoardPanel(sp.board);
            GameBoard gb = new GameBoard(single);
            gb.setVisible(true);

        }

        if (sp.Type.equals("Multiplayer")) {
            MultiBoardPanel multi = new MultiBoardPanel(sp.board);
            GameBoard gb = new GameBoard(multi);
            gb.setVisible(true);
        }


    }//GEN-LAST:event_loadButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadButton;
    private javax.swing.JTable savedPanelTable;
    // End of variables declaration//GEN-END:variables
}
